name: ai_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service Locator
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.18.1

  #Database
  floor: ^1.4.2

  #make request to api
  retrofit: ^4.0.1

  #Hooks
  flutter_hooks: ^0.20.3

  #cached image
  cached_network_image: ^3.2.0
  dio: ^5.0.0
  sqflite: ^2.3.0
  json_annotation: ^4.8.1
  built_value: ^8.6.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.1
  floor_generator: ^1.4.2
  build_runner: ^2.1.5
  json_serializable: ^6.7.1
  built_value_generator: ^8.6.3

flutter:

  uses-material-design: true
